const fruits = [
  {
    name: "Apple Pie",
    img: "/img/slice-of-apple-pie-2.jpg",
    prepTime: "20 minutes",
    cookTime: "45 minutes",
    servings: 8,
    ingredients: [
      "1 (14.1 ounce) package pastry for a 9-inch double-crust pie",
      "¾ cup white sugar, or more to taste",
      "1 cupsugar",
      "1 bar of butter",
      "3 cups peeled apples",
      "1 cup whole milk",
      "1 tsp vanilla extract",
      "1/8 tsp salt",
      "1 tsp baking powder",
      "2 cups all-purpose flour",
    ],
    instructions: [
      "Preheat oven to 425 degrees F (220 degrees C).",
      "Cut each apple in half horizontally.",
      "Cut each half in half vertically.",
      "Combine all ingredients in a large mixing bowl.",
      "Pour into a 9-inch pie plate.",
      "Bake at 425 degrees F (220 degrees C) for 45 minutes.",
      "Cool completely.",
      "Slice and serve immediately.",
    ],
  },
  {
    name: "No bake Mango pie",
    img: "/img/mango-royale-slice-2-4x5-1.jpg",
    prepTime: "20 minutes",
    cookTime: "45 minutes",
    servings: 8,
    ingredients: [
      "1 (14.1 ounce) package pastry for a 9-inch double-crust pie",
      "¾ cup white sugar, or more to taste",
      "1 cupsugar",
      "1 bar of butter",
      "3 cups peeled apples",
      "1 cup whole milk",
      "1 tsp vanilla extract",
      "1/8 tsp salt",
      "1 tsp baking powder",
      "2 cups all-purpose flour",
    ],
    instructions: [
      "Preheat oven to 425 degrees F (220 degrees C).",
      "Cut each apple in half horizontally.",
      "Cut each half in half vertically.",
      "Combine all ingredients in a large mixing bowl.",
      "Pour into a 9-inch pie plate.",
      "Bake at 425 degrees F (220 degrees C) for 45 minutes.",
      "Cool completely.",
      "Slice and serve immediately.",
    ],
  },
  {
    name: "Banana Muffins",
    img: "/img/banana-muffins-recipe-2.jpg",
    prepTime: "20 minutes",
    cookTime: "45 minutes",
    servings: 8,
    ingredients: [
      "1 (14.1 ounce) package pastry for a 9-inch double-crust pie",
      "¾ cup white sugar, or more to taste",
      "1 cupsugar",
      "1 bar of butter",
      "3 cups peeled apples",
      "1 cup whole milk",
      "1 tsp vanilla extract",
      "1/8 tsp salt",
      "1 tsp baking powder",
      "2 cups all-purpose flour",
    ],
    instructions: [
      "Preheat oven to 425 degrees F (220 degrees C).",
      "Cut each apple in half horizontally.",
      "Cut each half in half vertically.",
      "Combine all ingredients in a large mixing bowl.",
      "Pour into a 9-inch pie plate.",
      "Bake at 425 degrees F (220 degrees C) for 45 minutes.",
      "Cool completely.",
      "Slice and serve immediately.",
    ],
  },
  {
    name: "Blueberry Smoothie",
    img: "/img/Blueberry-Smoothie-Recipe-1-1200.jpg",
    prepTime: "20 minutes",
    cookTime: "45 minutes",
    servings: 8,
    ingredients: [
      "1 (14.1 ounce) package pastry for a 9-inch double-crust pie",
      "¾ cup white sugar, or more to taste",
      "1 cupsugar",
      "1 bar of butter",
      "3 cups peeled apples",
      "1 cup whole milk",
      "1 tsp vanilla extract",
      "1/8 tsp salt",
      "1 tsp baking powder",
      "2 cups all-purpose flour",
    ],
    instructions: [
      "Preheat oven to 425 degrees F (220 degrees C).",
      "Cut each apple in half horizontally.",
      "Cut each half in half vertically.",
      "Combine all ingredients in a large mixing bowl.",
      "Pour into a 9-inch pie plate.",
      "Bake at 425 degrees F (220 degrees C) for 45 minutes.",
      "Cool completely.",
      "Slice and serve immediately.",
    ],
  },
  {
    name: "Orange Cake",
    img: "/img/orange-cake.jpeg",
    prepTime: "20 minutes",
    cookTime: "45 minutes",
    servings: 8,
    ingredients: [
      "1 (14.1 ounce) package pastry for a 9-inch double-crust pie",
      "¾ cup white sugar, or more to taste",
      "1 cupsugar",
      "1 bar of butter",
      "3 cups peeled apples",
      "1 cup whole milk",
      "1 tsp vanilla extract",
      "1/8 tsp salt",
      "1 tsp baking powder",
      "2 cups all-purpose flour",
    ],
    instructions: [
      "Preheat oven to 425 degrees F (220 degrees C).",
      "Cut each apple in half horizontally.",
      "Cut each half in half vertically.",
      "Combine all ingredients in a large mixing bowl.",
      "Pour into a 9-inch pie plate.",
      "Bake at 425 degrees F (220 degrees C) for 45 minutes.",
      "Cool completely.",
      "Slice and serve immediately.",
    ],
  },
  {
    name: "Kiwi Jam",
    img: "/img/kiwi-jam.webp",
    prepTime: "10 minutes",
    cookTime: "20 minutes",
    servings: 20,
    ingredients: [
      "1 (14.1 ounce) package pastry for a 9-inch double-crust pie",
      "¾ cup white sugar, or more to taste",
      "1 cupsugar",
      "1 bar of butter",
      "3 cups peeled apples",
      "1 cup whole milk",
      "1 tsp vanilla extract",
      "1/8 tsp salt",
      "1 tsp baking powder",
      "2 cups all-purpose flour",
    ],
    instructions: [
      "Preheat oven to 425 degrees F (220 degrees C).",
      "Cut each apple in half horizontally.",
      "Cut each half in half vertically.",
      "Combine all ingredients in a large mixing bowl.",
      "Pour into a 9-inch pie plate.",
      "Bake at 425 degrees F (220 degrees C) for 45 minutes.",
      "Cool completely.",
      "Slice and serve immediately.",
    ],
  },
  {
    name: "Strawberry Shortcake",
    img: "/img/strawberry-shortcake-whipped-cream-biscuits.jpg",
    prepTime: "20 minutes",
    cookTime: "45 minutes",
    servings: 8,
    ingredients: [
      "1 (14.1 ounce) package pastry for a 9-inch double-crust pie",
      "¾ cup white sugar, or more to taste",
      "1 cupsugar",
      "1 bar of butter",
      "3 cups peeled apples",
      "1 cup whole milk",
      "1 tsp vanilla extract",
      "1/8 tsp salt",
      "1 tsp baking powder",
      "2 cups all-purpose flour",
    ],
    instructions: [
      "Preheat oven to 425 degrees F (220 degrees C).",
      "Cut each apple in half horizontally.",
      "Cut each half in half vertically.",
      "Combine all ingredients in a large mixing bowl.",
      "Pour into a 9-inch pie plate.",
      "Bake at 425 degrees F (220 degrees C) for 45 minutes.",
      "Cool completely.",
      "Slice and serve immediately.",
    ],
  },
];

module.exports = {
  fruits,
};
