const meats = [
  {
    name: "Pepperoni Pizza",
    img: "/img/pepperoni-pizza-heart.png",
    worldCuisine: "Italian",
    flag: "🇮🇹",
    prepTime: "20 minutes",
    cookTime: "15 minutes",
    servings: 8,
    ingredients: [
      "1 lb pizza dough",
      "1/4 cup olive oil",
      "1 tsp garlic powder",
      "1 tsp onion powder",
      "200 g ground beef",
      "1/4 tsp salt",
      "1/4 tsp black pepper",
      "1/4 tsp ground black pepper",
      "1/4 tsp ground red pepper",
      "1/4 tsp dried oregano",
      "1/4 tsp dried basil",
      "1/2 can pizza sauce",
      "1/2 can black/green olives",
      "1/2 can artichokes",
      "300 g mozzarella cheese",
      "100 g pepperoni",
    ],
    instructions: [
      "Preheat oven to 425 degrees F (220 degrees C).",
      "Roll out pizza dough to 1/4-inch thickness.",
      "Brush with olive oil.",
      "Sprinkle garlic powder, onion powder, and ground beef evenly over dough.",
      "Sprinkle salt and pepper.",
      "Bake in preheated oven for 15 minutes.",
      "Sprinkle black pepper.",
      "Sprinkle red pepper.",
      "Sprinkle oregano and basil.",
      "Bake an additional 5 minutes.",
    ],
  },
  {
    name: "Shrimp",
    color: "red",
    readyToEat: true,
    img: "/img/louis-hansel-mVZ_gjm_TOk-unsplash.jpg",
    worldCuisine: "Spanish",
    flag: "🇪🇸",
  },
  {
    name: "Chicken",
    color: "beige",
    readyToEat: true,
    img: "/img/sam-moghadam-khamseh-VpOpy6QrDrs-unsplash.jpg",
    worldCuisine: "Portuguese",
    flag: "🇵🇹",
  },
  {
    name: "Scallops",
    color: "red",
    readyToEat: true,
    img: "/img/sebastian-coman-photography-rtJCcnZgdRg-unsplash.jpg",
    worldCuisine: "Greek",
    flag: "🇬🇷",
  },
  {
    name: "Pastrami",
    color: "red",
    readyToEat: true,
    img: "/img/sergey-kotenev-u8A5_tMO-fE-unsplash.jpg",
    worldCuisine: "Italian",
    flag: "🇮🇹",
  },
  {
    name: "Carpaccio",
    color: "red",
    readyToEat: false,
    img: "/img/douglas-lopez-uOooiTi5hYk-unsplash.jpg",
    worldCuisine: "Italian",
    flag: "🇮🇹",
  },
  {
    name: "Prosciutto",
    color: "red",
    readyToEat: false,
    img: "/img/allan-francis-kouNxFstszs-unsplash.jpg",
    worldCuisine: "Italian",
    flag: "🇮🇹",
  },
  {
    name: "Salmon",
    color: "salmon",
    readyToEat: false,
    img: "/img/caroline-attwood-bpPTlXWTOvg-unsplash.jpg",
    worldCuisine: "Norwegian",
    flag: "🇳🇴",
  },
  {
    name: "Trout",
    color: "Gray",
    readyToEat: false,
    img: "/img/AdobeStock_612387875.jpeg",
    worldCuisine: "English",
    flag: "🇬🇧",
  },
  {
    name: "Pork",
    color: "red",
    readyToEat: false,
    img: "/img/karyna-panchenko-YSfEC5DSy08-unsplash.jpg",
    worldCuisine: "American",
    flag: "🇺🇸",
  },
  {
    name: "Beef Briskette",
    color: "red",
    readyToEat: false,
    img: "/img/natalia-gusakova-gqUFXms9FYs-unsplash.jpg",
    worldCuisine: "American",
    flag: "🇺🇸",
  },
];

module.exports = {
  meats,
};
