const veggies = [
  {
    name: "Steamed Carrots with Lemon-Dill Vinaigrette",
    img: "/img/glazed-carrots.jpeg",
    prepTime: "10 minutes",
    cookTime: "10 minutes",
    servings: 8,
    ingredients: [
      "Zest and juice of 1 medium lemon",
      "1 tablespoon Dijon mustard",
      "1 teaspoon red wine vinegar",
      "1 teaspoon honey",
      "1/3 cup extra-virgin olive oil",
      "3 tablespoons chopped fresh dill",
      "Kosher salt",
      "3 pounds carrots with greens trimmed to 1-inch",
    ],
    instructions: [
      "1 -Whisk together the lemon juice, Dijon mustard, vinegar and honey in a medium bowl until combined. Slowly pour in the olive oil, whisking constantly, until the vinaigrette is smooth and thickened. Stir in the chopped dill, lemon zest and 1/2 teaspoon salt. Set aside.",
      "Fill a medium wide-mouthed pot with 2 inches of water. Set a collapsible steamer basket insert into the pot, then bring to a simmer over medium-high heat.",
      "Put the carrots in the steamer basket and cook, covered, until tender when pierced with a knife, about 8 minutes. Gently toss the warm carrots with the dressing in a large shallow serving dish. Allow the dressing to absorb into the carrots for 5 minutes before serving.",
    ],
  },
  {
    name: "Italian Peas",
    img: "/img/artie-kostenko-Sgnhru4-z78-unsplash.jpg",
    prepTime: "10 minutes",
    cookTime: "10 minutes",
    servings: 6,
    ingredients: [
      "2 tablespoons olive oil",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "16 ounces frozen green peas",
      "1 tablespoon chicken stock",
      "salt and ground black pepper to taste",
    ],
    instructions: [
      "1- Gather all ingredients.",
      "2 - Heat olive oil in a skillet over medium heat. Stir in onion; cook until softened, about 5 minutes. Stir in garlic and cook for 1 minute.",
      "3 - Add frozen peas and stir in stock. Season with salt and pepper. Cover and cook until the peas are tender, about 5 minutes.",
    ],
  },
  {
    name: "Tomatoes Greek Pizza",
    img: "/img/greek-pizza.webp",
    prepTime: "10 minutes",
    cookTime: "10 minutes",
    servings: 8,
    ingredients: [
      "Zest and juice of 1 medium lemon",
      "1 tablespoon Dijon mustard",
      "1 teaspoon red wine vinegar",
      "1 teaspoon honey",
      "1/3 cup extra-virgin olive oil",
      "3 tablespoons chopped fresh dill",
      "Kosher salt",
      "3 pounds carrots with greens trimmed to 1-inch",
    ],
    instructions: [
      "1 -Whisk together the lemon juice, Dijon mustard, vinegar and honey in a medium bowl until combined. Slowly pour in the olive oil, whisking constantly, until the vinaigrette is smooth and thickened. Stir in the chopped dill, lemon zest and 1/2 teaspoon salt. Set aside.",
      "Fill a medium wide-mouthed pot with 2 inches of water. Set a collapsible steamer basket insert into the pot, then bring to a simmer over medium-high heat.",
      "Put the carrots in the steamer basket and cook, covered, until tender when pierced with a knife, about 8 minutes. Gently toss the warm carrots with the dressing in a large shallow serving dish. Allow the dressing to absorb into the carrots for 5 minutes before serving.",
    ],
  },
  {
    name: "Stuffed Bell Peppers",
    img: "/img/stuffed-bell-peppers.webp",
    prepTime: "10 minutes",
    cookTime: "10 minutes",
    servings: 8,
    ingredients: [
      "Zest and juice of 1 medium lemon",
      "1 tablespoon Dijon mustard",
      "1 teaspoon red wine vinegar",
      "1 teaspoon honey",
      "1/3 cup extra-virgin olive oil",
      "3 tablespoons chopped fresh dill",
      "Kosher salt",
      "3 pounds carrots with greens trimmed to 1-inch",
    ],
    instructions: [
      "1 -Whisk together the lemon juice, Dijon mustard, vinegar and honey in a medium bowl until combined. Slowly pour in the olive oil, whisking constantly, until the vinaigrette is smooth and thickened. Stir in the chopped dill, lemon zest and 1/2 teaspoon salt. Set aside.",
      "Fill a medium wide-mouthed pot with 2 inches of water. Set a collapsible steamer basket insert into the pot, then bring to a simmer over medium-high heat.",
      "Put the carrots in the steamer basket and cook, covered, until tender when pierced with a knife, about 8 minutes. Gently toss the warm carrots with the dressing in a large shallow serving dish. Allow the dressing to absorb into the carrots for 5 minutes before serving.",
    ],
  },
  {
    name: "Stuffed Cabbage Rolls",
    img: "/img/stuffed-cabbage-rolls.jpeg",
    prepTime: "10 minutes",
    cookTime: "10 minutes",
    servings: 8,
    ingredients: [
      "Zest and juice of 1 medium lemon",
      "1 tablespoon Dijon mustard",
      "1 teaspoon red wine vinegar",
      "1 teaspoon honey",
      "1/3 cup extra-virgin olive oil",
      "3 tablespoons chopped fresh dill",
      "Kosher salt",
      "3 pounds carrots with greens trimmed to 1-inch",
    ],
    instructions: [
      "1 -Whisk together the lemon juice, Dijon mustard, vinegar and honey in a medium bowl until combined. Slowly pour in the olive oil, whisking constantly, until the vinaigrette is smooth and thickened. Stir in the chopped dill, lemon zest and 1/2 teaspoon salt. Set aside.",
      "Fill a medium wide-mouthed pot with 2 inches of water. Set a collapsible steamer basket insert into the pot, then bring to a simmer over medium-high heat.",
      "Put the carrots in the steamer basket and cook, covered, until tender when pierced with a knife, about 8 minutes. Gently toss the warm carrots with the dressing in a large shallow serving dish. Allow the dressing to absorb into the carrots for 5 minutes before serving.",
    ],
  },
  {
    name: "Easy Arugula Salad",
    img: "/img/easy-arugula-salad.webp",
    prepTime: "20 minutes",
    cookTime: "5 minutes",
    servings: 6,
    ingredients: [
      "1 (14.1 ounce) package pastry for a 9-inch double-crust pie",
      "¾ cup white sugar, or more to taste",
      "1 cupsugar",
      "1 bar of butter",
      "3 cups peeled apples",
      "1 cup whole milk",
      "1 tsp vanilla extract",
      "1/8 tsp salt",
      "1 tsp baking powder",
      "2 cups all-purpose flour",
    ],
    instructions: [
      "Preheat oven to 425 degrees F (220 degrees C).",
      "Cut each apple in half horizontally.",
      "Cut each half in half vertically.",
      "Combine all ingredients in a large mixing bowl.",
      "Pour into a 9-inch pie plate.",
      "Bake at 425 degrees F (220 degrees C) for 45 minutes.",
      "Cool completely.",
      "Slice and serve immediately.",
    ],
  },
  {
    name: "Layer Carrot Cake",
    img: "/img/layer-carrot-cake-3.jpg",
    prepTime: "20 minutes",
    cookTime: "45 minutes",
    servings: 8,
    ingredients: [
      "1 (14.1 ounce) package pastry for a 9-inch double-crust pie",
      "¾ cup white sugar, or more to taste",
      "1 cupsugar",
      "1 bar of butter",
      "3 cups peeled apples",
      "1 cup whole milk",
      "1 tsp vanilla extract",
      "1/8 tsp salt",
      "1 tsp baking powder",
      "2 cups all-purpose flour",
    ],
    instructions: [
      "Preheat oven to 425 degrees F (220 degrees C).",
      "Cut each apple in half horizontally.",
      "Cut each half in half vertically.",
      "Combine all ingredients in a large mixing bowl.",
      "Pour into a 9-inch pie plate.",
      "Bake at 425 degrees F (220 degrees C) for 45 minutes.",
      "Cool completely.",
      "Slice and serve immediately.",
    ],
  },
];

module.exports = {
  veggies,
};
