const worldCuisines = [
    {
      name: "Onion soup",
      worldCuisine: "French",
      readyToEat: true,
      img: "/img/french-onion-soup.webp",
      countryOfOrigin: 'France',
      flag: "🇫🇷",
    },
    {
      name: "Sushi",
      worldCuisine: "Japanese",
      readyToEat: true,
      img: "/img/sushi.webp",
      countryOfOrigin: 'Japan',
      flag: "🇯🇵",
    },
    {
      name: "Poutine",
      worldCuisine: "Canadian",
      readyToEat: true,
      img: "/img/poutine.webp",
      countryOfOrigin: 'Canada',
      flag: "🇨🇦",
    },
    {
      name: "Steak and potatoes",
      worldCuisine: "English",
      readyToEat: true,
      img: "/img/SteakPotatoesMealPrep3_1200x.webp",
      countryOfOrigin: 'France',
      flag: "🇫🇷",
    },
    {
      name: "Galician Stew",
      worldCuisine: "Spanish",
      readyToEat: true,
      img: "/img/louis-hansel-mVZ_gjm_TOk-unsplash.jpg",
      countryOfOrigin: 'Spain',
      flag: "🇪🇸",
    },
    {
      name: "Gyros",
      worldCuisine: "Greek",
      readyToEat: true,
      img: "/img/Greek-Chicken-KabobsIMG_9979.jpg.webp",
      countryOfOrigin: 'Greece',
      flag: "🇬🇷",
    },
    {
      name: "Bolognese Pasta",
      worldCuisine: "Italian",
      readyToEat: false,
      img: "/img/greek-pizza.webp",
      countryOfOrigin: 'Italy',
      flag: "🇮🇹",
    },
    {
      name: "Tacos",
      worldCuisine: "Mexican",
      readyToEat: false,
      img: "/img/beef-barbacoa.webp",
      countryOfOrigin: 'Mexico',
      flag: "🇲🇽",
    },
    {
      name: "Garlic Smoked Pork",
      worldCuisine: "french",
      readyToEat: true,
      img: "/img/karyna-panchenko-YSfEC5DSy08-unsplash.jpg",
      countryOfOrigin: 'France',
      flag: "🇫🇷",
    },
    {
      name: "New York Sirloin Steak",
      worldCuisine: "American",
      readyToEat: true,
      img: "/img/natalia-gusakova-gqUFXms9FYs-unsplash.jpg",
      countryOfOrigin: 'USA',
      flag: "🇺🇸",
    },
    {
      name: "Paella",
      worldCuisine: "Spanish",
      readyToEat: true,
      img: "/img/paella.jpg",
      countryOfOrigin: 'Spain',
      flag: "🇪🇸",
    },
    {
      name: "Glazed Salmon",
      worldCuisine: "Norwegian",
      readyToEat: true,
      img: "/img/caroline-attwood-bpPTlXWTOvg-unsplash.jpg",
      countryOfOrigin: 'Norway',
      flag: "🇳🇴",
    },
    {
      name: "Buffalo Chicken Wings",
      worldCuisine: "American",
      readyToEat: true,
      img: "/img/buffalo-chicken-wings.webp",
      countryOfOrigin: 'USA',
      flag: "🇺🇸",
    },
    {
      name: "Pad Thai",
      worldCuisine: "Thai",
      readyToEat: true,
      img: "/img/Pad-Thai.jpeg",
      countryOfOrigin: 'Thailand',
      flag: "🇹🇭",
    },
  ];
  
  module.exports = {
    worldCuisines,
  };
  